### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by fi8er1** [byteShaft/neon#35]
A. Notification intent only works when the app is foreground.

B. Notification intent totally fails after sleep and awake by power button.
Steps to reproduce: 
1: Launch the Application.
2: Turn the flash On.
3: Press the power button to standby and then again to wake the device.
4: Unlock the device and the app is foreground as it was.
5: Pull down the notification panel and tap.
6: Shiiii.....!

C. Notification intent should not exit the app if it's foreground.

Tested on Moto X 2013

**Comment by fi8er1** [comment]
( B ) Can also be produced by 
1. Launch the App turn it On and Off again.
2. Put the App to background and foreground again.
3. Turn it On.
4. Tap the notification and it won't work.

Seems related.

**Comment by om26er** [comment]
Bug is fixed in master.
