### ISSUE TITLE
Torch Turnoff when screen gets off or phone get locked. 

### ISSUE THREAD

**Issue by s9iper1** [byteShaft/neon#44]
its a bug in 2.3.5 when  we  turn on light and leave it.
after some moments when the screen turn off and phone gets locked . Torch turns off and  the  app is still showing that torch is On and there is also surface Holder present.

**Comment by fi8er1** [comment]
imbal! lakh do laanat teray moun tay!

**Comment by fi8er1** [comment]
Issue Fixed.
