### ISSUE TITLE
Abnormal behavior on Nexus 5

### ISSUE THREAD

**Issue by imranhakeem** [byteShaft/neon#45]
Bug: In App, if you tap the button, torch will first blink for 0.5 seconds while showing off position on Neon Button then turns on automatically like normal. 
Same behavior on Widget as well.

How to Reproduce:
1. Open the App by clicking on Neon Icon :P.
2. Tap the Neon button.
3. Bam! 

Possible Reason: onClick is automatically being called for two times on TurnON :/
2nd possible Reason: It's conflicting with the widget state.
3rd Possible Reason: The application may be doing too much work on its main thread :P

**Comment by fi8er1** [comment]
Fixed.
