### ISSUE TITLE
Widget stops receiving input

### ISSUE THREAD

**Issue by om26er** [byteShaft/neon#49]
In some conditions the desktop widget stops responding. One of the cases is when the launcher is restarted due to low memory.
1. Make sure to put neon widget on the desktop
2. Open settings > Apps > All and force stop Launcher
3. Go back to desktop and tap on the neon torch widget.

What happens: Nothing
What should happen: well, toggle the torch on/off ?

**Comment by imranhakeem** [comment]
Aap chawal hain

**Comment by om26er** [comment]
Fixed in master.
